name: OpenPDF Maven Build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21, 24, 25, '26-ea'] 
    name: Build with Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Check Maven version and directory contents
        run: |
          mvn -v
          echo "** ls **"
          pwd && ls -l

      - name: Build with Maven
        run: mvn -B install --file pom.xml
